### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JohnMarksRH**
I made some edits. Further clarifications will help to make the steps even clearer. A clearer title is required.

@rgolangh

### CODE REVIEW

**Comment by rollandf** [comment]
@JohnMarksRH this github repo is just a mirror. In order to contribute, please use gerrit.
https://gerrit.ovirt.org/#/q/project:ovirt-vdsmfake

**Comment by rgolangh** [comment]
@rollandf I asked @JohnMarksRH to make a pull request as it is easier for him to review. I'll port that to gerrit. @rollandf thanks for noticing and commenting!

**Comment by rgolangh** [comment]
@rollandf gerrit.ovirt.org doesn't allow you to just peek a file in the browser and create a review request on it. This is one of the advantages of gh I like.

**Comment by rgolangh** [comment]
@JohnMarksRH  I converted this into a gerrit patch https://gerrit.ovirt.org/#/c/77310/2

**Pull request closed without merging**
